### ISSUE TITLE
How to change Password Policy

### ISSUE THREAD

**Issue by KoichiNakata** [EisenVault/ev-user-management#3]
Thank you for brilliant addon module.
I want to change password policy a little bit. Could you please kindly let me know how to do?

**Comment by monicakumari** [comment]
Hello,
You can change password policy by making changes in "values" variable of "validatePassword" function inside "change-password.post.json.js" file.
also, need to make changes in "users.js" and "reset-pass-lib.js" files for the same variable "values".

Thanks.
